# Generated by Django 5.1.4 on 2025-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='user.jpg', upload_to='profile_photos'),
        ),
    ]
